import { About, Cases, Footer, Hero, Navbar } from '@/components';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid grid-cols-12">
        <div className="col-start-2 col-end-12">
          <Navbar />
          <Hero />
          <About />
          <Cases />
        </div>
      </div>
      <Footer />
    </>
  );
}
